const LOGIN = "login";
const GET_HOME_DATA = "home";
const CATEGORIES = "categories";
const FAVORITE = "favorites";
const PROFILE = "profile";
const REGISTER = "register";
const UPDATE_PROFILE= "update-profile";
const SEARCH_PRODUCT = "products/search";
const CATEGORY_PRODUCTS = "products?category_id=";
const CART = "carts";
const UPDATE_CART = "carts/";